services:
  postgres:
    image: postgres:15
    container_name: linkly-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linkly_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  postgres-test:
    image: postgres:15
    container_name: linkly-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linkly_test_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: linkly-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - postgres-test

volumes:
  postgres_data:
  postgres_test_data:
